### ISSUE TITLE
Bug: Coherence only works on gettext `0.13.1`

### ISSUE THREAD

**Issue by StephanMeijer** [smpallen99/coherence#346]
See #339 
See https://github.com/smpallen99/coherence/pull/344

```
== Compilation error in file lib/coherence_demo_web/coherence_messages.ex ==
** (ArgumentError) *gettext macros expect translation keys (msgid and msgid_plural) and
domains to expand to strings at compile-time, but the given msgid
doesn't.

Dynamic translations should be avoided as they limit gettext's
ability to extract translations from your source code. If you are
sure you need dynamic lookup, you can use the functions in the Gettext
module:

    string = "hello world"
    Gettext.gettext(CoherenceDemoWeb.Gettext, string)

    (gettext) lib/gettext/compiler.ex:231: Gettext.Compiler.expand_to_binary/4
    expanding macro: CoherenceDemoWeb.Gettext.dgettext_noop/2
    lib/coherence_demo_web/coherence_messages.ex:75: CoherenceDemoWeb.Coherence.Messages.you_are_using_an_invalid_security_token/0
    expanding macro: CoherenceDemoWeb.Gettext.dgettext/2
    lib/coherence_demo_web/coherence_messages.ex:75: CoherenceDemoWeb.Coherence.Messages.you_are_using_an_invalid_security_token/0
    (elixir) lib/kernel/parallel_compiler.ex:198: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/6
```

**Comment by StephanMeijer** [comment]
Thanks for your answer!
